### ISSUE TITLE
Undefined variables in a condition results in a syntax error 

### ISSUE THREAD

**Issue by freesh** [freesh/butler#23]
```
[Symfony\Component\ExpressionLanguage\SyntaxError]
Variable "gitpush" is not valid around position 19 for expression `gitcommit == 1 && gitpush == 1`.
```

To prevent this, it would be useful to predefine some variables.

In this case, the variable git-push is created in the "Git ask push" task if the condition "gitcommit=1" is true. But if git-commit is false, git-push will never be created.
Here the example config:

```yaml
'Git ask push':
  class: \Butler\Task\InputTask
  task: confirmation
  options:
    gitcommit: 'Create initial git commit?'

'Git commit':
  class: \Butler\Task\GitTask
  task: commit
  options:
    message: 'initial commit'
  condition: 'gitcommit == 1'

'Git add remote':
  class: \Butler\Task\GitTask
  task: remoteAdd
  options:
    origin: origin
  condition: 'gitcommit == 1'

'Git ask push':
  class: \Butler\Task\InputTask
  task: confirmation
  options:
    gitpush: 'Execute git push now?'
  condition: 'gitcommit == 1'

'Git push':
  class: \Butler\Task\GitTask
  task: push
  options:
    params:
      - '-u'
    origin: origin
    branch: master
  condition: 'gitpush == 1'
```
